configType = "custom"
l1ChainID = 1337
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-b112b16f8939fbb732c0693de3d3bd1e8e3e2f0771f91d5ab300a6c9b7b1af73.tar.gz"
l2ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-b112b16f8939fbb732c0693de3d3bd1e8e3e2f0771f91d5ab300a6c9b7b1af73.tar.gz"

[superchainRoles]
proxyAdminOwner = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
protocolVersionsOwner = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
guardian = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
superchainProxyAdminOwner = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
superchainGuardian = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
challenger = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"

[[chains]]
id = "0x000000000000000000000000000000000000000000000000000000000000000d"
baseFeeVaultRecipient = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
l1FeeVaultRecipient = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
sequencerFeeVaultRecipient = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
gasLimit = 60000000
eip1559DenominatorCanyon = 250
eip1559Denominator = 50
eip1559Elasticity = 6

[chains.roles]
l1ProxyAdminOwner = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
l2ProxyAdminOwner = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
systemConfigOwner = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
unsafeBlockSigner = "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
batcher = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
proposer = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
challenger = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"