name: playground-action

on:
  workflow_dispatch:

jobs:
  run-builder-playground-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run builder-playground
        uses: flashbots/builder-playground-action@v1
        with:
          version: latest
          detached: false
          recipe: l1
          args: --timeout 5s
